---
project_host: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"

### api

project_api_version: latest
project_api_image: levonet/cp-measurement:{{ project_api_version }}
project_api_name: cp-measurement
project_api_hostname: localhost
project_api_public_port: 4150
project_api_port_pool: 4151-4199
project_api_volumes:
- /opt/tg-checkpromise-bot/db/session.json:/app/db/telegram-session.json
- /opt/cp-viber-bot/db/session.json:/app/db/viber-session.json
project_api_nginx_conf: |
  server {
      include include/listen;
      # include include/listen_ssl;
      server_name {{ project_api_hostname }};
      location / {
          proxy_pass http://{{ project_host }}:{{ project_api_public_port }};
      }
  }

### grafana

project_grafana_name: cp-grafana
project_grafana_image: grafana/grafana:6.4.3
project_grafana_hostname: localhost
project_grafana_password:
